spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 1234

mail:
  host: https://smtp.gmail.com
  port: 5761

logging:
  level:
    org:
      springframework:
        boot:
          devtools: DEBUG
